#!/usr/bin/python3
#todo root
import sys
import os

# Make running from the project root work by adding `src/` to sys.path
here = os.path.dirname(os.path.abspath(os.path.realpath(__file__)))
srcdir = os.path.join(here, 'src')
if srcdir not in sys.path:
    sys.path.insert(0, srcdir)

from main import main

if __name__ == '__main__':
    if sys.argv[0].endswith('.exe'):
        sys.argv[0] = sys.argv[0][:-4]
    sys.exit(main())
